[package]
name = "voting_contract"
type = "contract"
authors = ["Satyam Bansal"]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.87.2", directory = "noir-projects/aztec-nr/aztec" }
